# APW 1.0
# Integración continua
# Crear un lanzamiento del producto
# Tomado de https://www.learnstorybook.com/design-systems-for-developers

name: Release

# Esta acción se ejecuta al mezclar una solicitud de extracción (pull request) con la rama principal (master)
on:
  push:
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2

      - name: Preparar el repositorio
        run: git fetch --unshallow --tags

      - name: Configurar el paquete para GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Crear un lanzamiento del producto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          CI= npm run build
          npx auto shipit
